import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
const DashboardSkeleton = () => {
    return (_jsxs("div", { className: "flex min-h-screen bg-[#f5f5f6]", children: [_jsxs("aside", { className: "w-64 bg-[#1F1F1F] p-5 space-y-10 hidden md:block", children: [_jsx("div", { className: "mb-2", children: _jsx(Skeleton, { height: 46, width: 210, baseColor: "#2c2c2c", highlightColor: "#3e3e3e" }) }), _jsx("div", { className: "mb-5", children: _jsx(Skeleton, { height: 46, width: 210, baseColor: "#2c2c2c", highlightColor: "#3e3e3e" }) }), Array(12)
                        .fill(0)
                        .map((_, i) => (_jsx("div", { className: "mb-3", children: _jsx(Skeleton, { height: 34, width: 210, baseColor: "#2c2c2c", highlightColor: "#3e3e3e" }) }, i)))] }), _jsxs("main", { className: "flex-1 pb-6 py-1 ", children: [_jsxs("div", { className: "flex justify-between items-center border-b py-2 border-[#001B4429] px-6", children: [_jsx(Skeleton, { height: 40, width: 340 }), _jsxs("div", { className: "flex items-center space-x-7", children: [_jsxs("div", { className: "flex items-center gap-5", children: [_jsx(Skeleton, { height: 20, width: 90 }), _jsx(Skeleton, { height: 20, width: 90 })] }), _jsx(Skeleton, { circle: true, height: 50, width: 50 })] })] }), _jsx("div", { className: "bg-[white] py-4  mb-6 border-b border-[#001B4429] px-6", children: _jsx("h2", { children: "Overview" }) }), _jsx("div", { className: "grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-4 mb-8 px-3 md:h-[150px]", children: Array(4)
                            .fill(0)
                            .map((_, i) => (_jsxs("div", { className: "p-4 rounded-xl shadow bg-white space-y-3 relative", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsx(Skeleton, { circle: true, height: 25, width: 24 }), _jsx(Skeleton, { height: 14, width: 12 })] }), _jsx("div", { className: "mb-3", children: _jsx(Skeleton, { height: 17, width: 100 }) }), _jsx(Skeleton, { height: 32, width: 120 }), _jsx("div", { className: "absolute bottom-5 right-4", children: _jsx(Skeleton, { height: 28, width: 60, borderRadius: 16 }) })] }, i))) }), _jsxs("div", { className: "flex gap-5 md:flex-row flex-col px-3", children: [_jsxs("div", { className: "col-span-2 bg-white p-6 rounded-xl md:w-[930px] w-full shadow space-y-6 border border-[#001B4429]", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { className: "space-y-2", children: [_jsx(Skeleton, { height: 24, width: 180 }), " ", _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Skeleton, { height: 32, width: 100 }), " ", _jsx(Skeleton, { height: 24, width: 50, borderRadius: 999 }), " "] }), _jsx(Skeleton, { height: 16, width: 120 }), " "] }), _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Skeleton, { height: 36, width: 160, borderRadius: 7 }), _jsx(Skeleton, { height: 36, width: 100, borderRadius: 7 })] })] }), _jsx("div", { className: "flex items-end justify-between h-[250px] px-1", children: [240, 200, 160, 190, 170, 120, 150, 180, 100, 85, 115, 195].map((h, i) => (_jsx(Skeleton, { height: h, width: 44, borderRadius: 4 }, i))) })] }), _jsxs("div", { className: "bg-white py-4 px-5 rounded-lg shadow space-y-5 border border-[#001B4429] md:w-[290px] w-full", children: [_jsx(Skeleton, { height: 35, width: 190 }), Array(3)
                                        .fill(0)
                                        .map((_, i) => (_jsxs("div", { className: "space-y-2", children: [_jsx(Skeleton, { height: 30, width: 180, className: "rounded-md" }), " ", _jsx(Skeleton, { height: 20, width: 100, className: "rounded" }), " ", _jsx(Skeleton, { height: 15, width: 160, className: "rounded" }), " "] }, i)))] })] })] })] }));
};
export default DashboardSkeleton;
